language:       node_js

node_js:
    - "node"
    - "8.6.0"
    - "7"

sudo:           false

git:
    submodules: false
before_install:
- export TZ=Europe/Stockholm


notifications:
    email:      false
